  apiVersion: v1
  kind: Pod
  metadata:
    name: voting-app-pod
    namespace: default
    labels:
      name: voting-app-pod
      app: demo-voting-app
  spec:
    containers:
      - name: demo-voting-app
        image: dockersamples/examplevotingapp_vote
        ports:
          - containerPort: 80
